# Setup
title:               Pablo Arrabal Espinosa
tagline:             'Políticas y avisos legales'
description:         'En esta web se almacenan los documentos legales'
url:                 https://legal-86t.pages.dev
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pablo Arrabal Espinosa
  url:               https://twitter.com/nuoframework
  email:             contacto@pabloarrabal.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
